server:
  port: 9090

spring:
  application:
    name: NotificationService

  kafka:
    bootstrap-servers: localhost:29092
    topic: transaction

  mail:
    host: smtp.yandex.ru
    port: 465
    username: potovgosha@yandex.ru
    password: cxyzvymsclieboyg
    protocol: smtps
    debug: true
    send-to: evgenigolovach@yandex.ru