server:
  port: 8585

spring:
  application:
    name: TransactionService

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: myuser
    password: mypassword

  kafka:
    bootstrap-servers: localhost:29092
    topic: transaction
